config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trip_categories
  resources :trips
  get 'main/index'
  get 'welcome/index'
  get 'trips/new'
  get 'trips/edit'
  get 'devise/registrations/new'
  root 'users#home'
  get '/home' => 'users#home'
  post '/create' => 'users#create'
  post '/signin' => 'users#signin'
  get 'signup' => 'users#new'
  post '/new' => 'users#new'
  get 'devise/new' => 'devise/registrations#new'

  match '*path' => 'users#home', :via => :get
 
  # root 'welcome#index'
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	def new
	end

	def create
		@trip = Trip.new(trip_params)
 
	  	@trip.save
	  	redirect_to edit_trip_path(@trip)
	end

	def edit
		@trip = Trip.find(params[:id])
	end

	private 
		def trip_params
			params.require(:trip).permit(:name, :category)
		end


end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/edit.html.erb
<div class="container">
	<h1 class="mt-3"> Aviso de Salida </h1>

	<%= form_with model: @trip, local: true, class:"mt-3" do |form| %>
		<% if @trip.errors.any? %>
	    	<div id="error_explanation">
	      		<h2>
	        		<%= pluralize(@trip.errors.count, "error") %> prohibited
	        		this article from being saved:
	      		</h2>
	      		<ul>
	        		<% @trip.errors.full_messages.each do |msg| %>
	          			<li><%= msg %></li>
	        		<% end %>
	      		</ul>
	    	</div>
	  	<% end %>
 
		<div class="form-group mt-2">
			<div class="form-row align-items-center">
		    	<div class="col-auto my-1">
		    		<%= form.label :category, "Tipo de Actividad", :class=>"mr-sm-2" %>
		    		<%= form.select :category, options_for_select([['Senderismo', 1], ['Montañismo', 2], ['Escalada', 3], ['Trail Running', 4], ['Caminata fuera de senderos', 5],['Empanadismo Tradicional', 6]], :category), {}, {:class=> "custom-select mr-sm-2"}  %>
		    	</div>
		    </div>
			<div class="form-row align-items-center">
		    	<div class="col-10 mt-1">
		    		<%= form.label :name, "Título de la salida" %>
		    		<br>
		    		<%= form.text_field :name, placeholder: "K2 Invernal por la magic Line", class:"form-control" %>
		    	</div>
 			</div>

 			<% if :category == 1 %>


 				<div class="form-group">
					<label>Integrantes, Datos Médicos y de Contacto</label>
					<input type="text" class="form-control" placeholder="Edmundo Hilario, en solitario">
				</div>
			<% else %>
				<div class="form-group">
					<label>2 o +</label>
					<input type="text" class="form-control" placeholder="Edmundo Hilario, en solitario">
				</div>
			<% end %>

  			<div class="col mt-4 pl-0">
    			<%= form.submit "Guardar Aviso", :class=>"btn btn-primary col-5"%>
  			</div>

  		</div>
	<% end %>










	  <div class="form-group mt-5">
	    <label for="exampleFormControlInput1">Email address</label>
	    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
	  </div>
	  <div class="form-group">
	    <label for="exampleFormControlSelect1">Example select</label>
	    <select class="form-control" id="exampleFormControlSelect1">
	      <option>1</option>
	      <option>2</option>
	      <option>3</option>
	      <option>4</option>
	      <option>5</option>
	    </select>
	  </div>
	  <div class="form-group">
	    <label for="exampleFormControlSelect2">Example multiple select</label>
	    <select multiple class="form-control" id="exampleFormControlSelect2">
	      <option>1</option>
	      <option>2</option>
	      <option>3</option>
	      <option>4</option>
	      <option>5</option>
	    </select>
	  </div>
	  <div class="form-group">
	    <label for="exampleFormControlTextarea1">Example textarea</label>
	    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
	  </div>


	  <div class="form-group">
	    <label for="exampleFormControlFile1">Example file input</label>
	    <input type="file" class="form-control-file" id="exampleFormControlFile1">
	  </div>
	<input class="form-control form-control-lg" type="text" placeholder=".form-control-lg">
	<input class="form-control" type="text" placeholder="Default input">
	<input class="form-control form-control-sm" type="text" placeholder=".form-control-sm">
	<select class="form-control form-control-lg">
	  <option>Large select</option>
	</select>
	<select class="form-control">
	  <option>Default select</option>
	</select>
	<select class="form-control form-control-sm">
	  <option>Small select</option>
	</select>

	<div class="form-check">
	  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
	  <label class="form-check-label" for="defaultCheck1">
	    Default checkbox
	  </label>
	</div>
	<div class="form-check">
	  <input class="form-check-input" type="checkbox" value="" id="defaultCheck2" disabled>
	  <label class="form-check-label" for="defaultCheck2">
	    Disabled checkbox
	  </label>
	</div>

	<div class="form-check">
	  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
	  <label class="form-check-label" for="exampleRadios1">
	    Default radio
	  </label>
	</div>
	<div class="form-check">
	  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
	  <label class="form-check-label" for="exampleRadios2">
	    Second default radio
	  </label>
	</div>
	<div class="form-check disabled">
	  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios3" value="option3" disabled>
	  <label class="form-check-label" for="exampleRadios3">
	    Disabled radio
	  </label>
	</div>

	<div class="form-check form-check-inline">
	  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
	  <label class="form-check-label" for="inlineCheckbox1">1</label>
	</div>
	<div class="form-check form-check-inline">
	  <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
	  <label class="form-check-label" for="inlineCheckbox2">2</label>
	</div>
	<div class="form-check form-check-inline">
	  <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3" disabled>
	  <label class="form-check-label" for="inlineCheckbox3">3 (disabled)</label>
	</div>

	<div class="form-check form-check-inline">
	  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
	  <label class="form-check-label" for="inlineRadio1">1</label>
	</div>
	<div class="form-check form-check-inline">
	  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
	  <label class="form-check-label" for="inlineRadio2">2</label>
	</div>
	<div class="form-check form-check-inline">
	  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3" disabled>
	  <label class="form-check-label" for="inlineRadio3">3 (disabled)</label>
	</div>

	<div class="form-group">
	    <label for="formGroupExampleInput">Example label</label>
	    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input">
	  </div>
	  <div class="form-group">
	    <label for="formGroupExampleInput2">Another label</label>
	    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
	  </div>

	    <div class="row">
	    <div class="col">
	      <input type="text" class="form-control" placeholder="First name">
	    </div>
	    <div class="col">
	      <input type="text" class="form-control" placeholder="Last name">
	    </div>
	  </div>

	   <div class="form-row">
	    <div class="form-group col-md-6">
	      <label for="inputEmail4">Email</label>
	      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
	    </div>
	    <div class="form-group col-md-6">
	      <label for="inputPassword4">Password</label>
	      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="inputAddress">Address</label>
	    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
	  </div>
	  <div class="form-group">
	    <label for="inputAddress2">Address 2</label>
	    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
	  </div>
	  <div class="form-row">
	    <div class="form-group col-md-6">
	      <label for="inputCity">City</label>
	      <input type="text" class="form-control" id="inputCity">
	    </div>
	    <div class="form-group col-md-4">
	      <label for="inputState">State</label>
	      <select id="inputState" class="form-control">
	        <option selected>Choose...</option>
	        <option>...</option>
	      </select>
	    </div>
	    <div class="form-group col-md-2">
	      <label for="inputZip">Zip</label>
	      <input type="text" class="form-control" id="inputZip">
	    </div>
	  </div>
	  <div class="form-group">
	    <div class="form-check">
	      <input class="form-check-input" type="checkbox" id="gridCheck">
	      <label class="form-check-label" for="gridCheck">
	        Check me out
	      </label>
	    </div>
	  </div>
	  <button type="submit" class="btn btn-primary">Sign in</button>


	    <div class="form-row align-items-center">
	    <div class="col-auto my-1">
	      <label class="mr-sm-2" for="inlineFormCustomSelect">Preference</label>
	      <select class="custom-select mr-sm-2" id="inlineFormCustomSelect">
	        <option selected>Choose...</option>
	        <option value="1">One</option>
	        <option value="2">Two</option>
	        <option value="3">Three</option>
	      </select>
	    </div>
	    <div class="col-auto my-1">
	      <div class="custom-control custom-checkbox mr-sm-2">
	        <input type="checkbox" class="custom-control-input" id="customControlAutosizing">
	        <label class="custom-control-label" for="customControlAutosizing">Remember my preference</label>
	      </div>
	    </div>
	    <div class="col-auto my-1">
	      <button type="submit" class="btn btn-primary">Submit</button>
	    </div>
	  </div>

	  <label for="inputPassword5">Password</label>
	<input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock">
	<small id="passwordHelpBlock" class="form-text text-muted">
	  Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
	</small>
	</form>
</div>

app/views/trips/new.html.erb
<div class="container">
	<h1 class="mt-3"> Aviso de Salida </h1>

	<%= form_with scope: :trip, url: trips_path, local: true, class:"mt-3" do |form| %>
		<div class="form-group mt-2">
			<div class="form-row align-items-center">
		    	<div class="col-auto my-1">
		    		<%= form.label :category, "Tipo de Actividad", :class=>"mr-sm-2" %>
		    		<%= form.select :category, options_for_select([['Senderismo', 1], ['Montañismo', 2], ['Escalada', 3], ['Trail Running', 4], ['Caminata fuera de senderos', 5],['Empanadismo Tradicional', 6]], 2), {}, {:class=> "custom-select mr-sm-2"}  %>
		    	</div>
		    </div>
			<div class="form-row align-items-center">
		    	<div class="col-10 mt-1">
		    		<%= form.label :name, "Título de la salida" %>
		    		<br>
		    		<%= form.text_field :name, placeholder: "K2 Invernal por la magic Line", class:"form-control" %>
		    	</div>
 			</div>
  			<div class="col mt-4 pl-0">
    			<%= form.submit "Crear Aviso", :class=>"btn btn-primary col-5"%>
  			</div>
  		</div>
	<% end %>
</div>