config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trip_categories
  resources :trips
  get 'main/index'
  get 'welcome/index'
  get 'trips/new'
  get 'trips/edit'
  get 'devise/registrations/new'
  root 'users#home'
  get '/home' => 'users#home'
  post '/create' => 'users#create'
  post '/signin' => 'users#signin'
  get 'signup' => 'users#new'
  post '/new' => 'users#new'
  get 'devise/new' => 'devise/registrations#new'

  match '*path' => 'users#home', :via => :get
 
  # root 'welcome#index'
end

app/models/trip_category.rb
class TripCategory < ApplicationRecord
end

app/controllers/trip_categories_controller.rb
class TripCategoriesController < ApplicationController
  before_action :set_trip_category, only: [:show, :edit, :update, :destroy]

  # GET /trip_categories
  # GET /trip_categories.json
  def index
    @trip_categories = TripCategory.all
  end

  # GET /trip_categories/1
  # GET /trip_categories/1.json
  def show
  end

  # GET /trip_categories/new
  def new
    @trip_category = TripCategory.new
  end

  # GET /trip_categories/1/edit
  def edit
  end

  # POST /trip_categories
  # POST /trip_categories.json
  def create
    @trip_category = TripCategory.new(trip_category_params)

    respond_to do |format|
      if @trip_category.save
        format.html { redirect_to @trip_category, notice: 'Trip category was successfully created.' }
        format.json { render :show, status: :created, location: @trip_category }
      else
        format.html { render :new }
        format.json { render json: @trip_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trip_categories/1
  # PATCH/PUT /trip_categories/1.json
  def update
    respond_to do |format|
      if @trip_category.update(trip_category_params)
        format.html { redirect_to @trip_category, notice: 'Trip category was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip_category }
      else
        format.html { render :edit }
        format.json { render json: @trip_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_categories/1
  # DELETE /trip_categories/1.json
  def destroy
    @trip_category.destroy
    respond_to do |format|
      format.html { redirect_to trip_categories_url, notice: 'Trip category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_category
      @trip_category = TripCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_category_params
      params.require(:trip_category).permit(:name)
    end
end

app/helpers/trip_categories_helper.rb
module TripCategoriesHelper
end

app/views/trip_categories/_form.html.erb
<%= form_with(model: trip_category, local: true) do |form| %>
  <% if trip_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip_category.errors.count, "error") %> prohibited this trip_category from being saved:</h2>

      <ul>
        <% trip_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trip_categories/edit.html.erb
<h1>Editing Trip Category</h1>

<%= render 'form', trip_category: @trip_category %>

<%= link_to 'Show', @trip_category %> |
<%= link_to 'Back', trip_categories_path %>

app/views/trip_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trip Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trip_categories.each do |trip_category| %>
      <tr>
        <td><%= trip_category.name %></td>
        <td><%= link_to 'Show', trip_category %></td>
        <td><%= link_to 'Edit', edit_trip_category_path(trip_category) %></td>
        <td><%= link_to 'Destroy', trip_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip Category', new_trip_category_path %>

app/views/trip_categories/new.html.erb
<h1>New Trip Category</h1>

<%= render 'form', trip_category: @trip_category %>

<%= link_to 'Back', trip_categories_path %>

app/views/trip_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trip_category.name %>
</p>

<%= link_to 'Edit', edit_trip_category_path(@trip_category) %> |
<%= link_to 'Back', trip_categories_path %>